version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: livraria-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Livraria
      MYSQL_USER: chris
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/MySQL/create.sql:/docker-entrypoint-initdb.d/create.sql

  app:
    build: .
    container_name: livraria-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:mysql://db:3306/Livraria
      - DB_USER=chris
      - DB_PASSWORD=1234

volumes:
  db_data:
