version: '3'

services:
  web:
    build: ./docker-img/site # caminho para o dockerfile da aplicação
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
    # gambiarra que eu nem sei o que faz pra tentar fazer funcionar
      - /home/chris/AreaDeTrabalho/Webinho/Livraria/target/Livraria.war:/usr/local/tomcat/webapps/Livraria.war
  db:
    image: mysql:5.6
    environment:
    # credenciais de acesso ao banco de dados sql
      MYSQL_DATABASE: Livraria
      MYSQL_USER: chris
      MYSQL_PASSWORD: 1234
    volumes:
      - /home/chris/AreaDeTrabalho/Webinho/Livraria/db/MySQL/create.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
      - "3306:3306"
